//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kapok.View.Wpf.Report.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataTableReportViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataTableReportViewModel() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kapok.View.Wpf.Report.Resources.DataTableReportViewModel", typeof(DataTableReportViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV file (*.csv)|*.csv ähnelt.
        /// </summary>
        internal static string SaveAsCsvFile_SaveFileDialogFilter {
            get {
                return ResourceManager.GetString("SaveAsCsvFile_SaveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as CSV file ähnelt.
        /// </summary>
        internal static string SaveAsCsvFile_Title {
            get {
                return ResourceManager.GetString("SaveAsCsvFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Excel file (*.xlsx)|*.xlsx ähnelt.
        /// </summary>
        internal static string SaveAsExcelFile_SaveFileDialogFilter {
            get {
                return ResourceManager.GetString("SaveAsExcelFile_SaveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as excel file ähnelt.
        /// </summary>
        internal static string SaveAsExcelFile_Title {
            get {
                return ResourceManager.GetString("SaveAsExcelFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string SendNotificationOnExportSuccessful_Caption {
            get {
                return ResourceManager.GetString("SendNotificationOnExportSuccessful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export successful. ähnelt.
        /// </summary>
        internal static string SendNotificationOnExportSuccessful_Message {
            get {
                return ResourceManager.GetString("SendNotificationOnExportSuccessful_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        internal static string SendNotificationOnExportSuccessfulRequestToOpen_Caption {
            get {
                return ResourceManager.GetString("SendNotificationOnExportSuccessfulRequestToOpen_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export successful. Shall the file be opened? ähnelt.
        /// </summary>
        internal static string SendNotificationOnExportSuccessfulRequestToOpen_Message {
            get {
                return ResourceManager.GetString("SendNotificationOnExportSuccessfulRequestToOpen_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error - Exception ähnelt.
        /// </summary>
        internal static string SendNotificationOnIOException_Caption {
            get {
                return ResourceManager.GetString("SendNotificationOnIOException_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An IO exception occured during the export. ähnelt.
        /// </summary>
        internal static string SendNotificationOnIOException_Message {
            get {
                return ResourceManager.GetString("SendNotificationOnIOException_Message", resourceCulture);
            }
        }
    }
}
